name: Terraform Multi Provider

on:
  push:
    branches:
    - testing
  workflow_dispatch:

env:
  TERRAFORM_VERSION: "1.13.3"

jobs:
 
  aws:
    name: Testing for AWS code
    runs-on: ubuntu-latest
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - uses: actions/checkout@v4
    - uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id    : ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token    : ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region           : us-east-1
    - run: terraform -chdir=./terraform/aws init
    - run: terraform -chdir=./terraform/aws validate
    - uses: bridgecrewio/checkov-action@master
      with:
        directory: ./terraform/aws
        framework: terraform
        output_format: cli
        output_file_path: console
        soft_fail: true

  azure:
    name: Testing for Azure code
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ env.TERRAFORM_VERSION }}
    - uses: actions/checkout@v4
    - run: terraform -chdir=./terraform/azure init
    - run: terraform -chdir=./terraform/azure validate
    - uses: bridgecrewio/checkov-action@master
      with:
        directory: ./terraform/azure
        framework: terraform
        output_format: cli
        output_file_path: console
        soft_fail: true